version: '3.8'
services:
 postgres:
  image: postgres
  container_name: dez-wk2-postgres-db
  environment:
    POSTGRES_USER: kestra
    POSTGRES_PASSWORD: k3str4
    POSTGRES_DB: postgres-zoomcamp
  ports:
    - "5436:5432"
  volumes:
    - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: